// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkkIUaeTOjCUqgyauXHp7JlLee9X4cyuM',
    appId: '1:893946047140:web:548abdd2cdb41a077ad431',
    messagingSenderId: '893946047140',
    projectId: 'voygers-9ec9b',
    authDomain: 'voygers-9ec9b.firebaseapp.com',
    storageBucket: 'voygers-9ec9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBithTlxBrRIdVb17ENdMG5diBJU-a6Xy8',
    appId: '1:893946047140:android:86ffb6ff458240317ad431',
    messagingSenderId: '893946047140',
    projectId: 'voygers-9ec9b',
    storageBucket: 'voygers-9ec9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLZU6ZQGz1NSgvtuJSfU57AkwdbPrIK3M',
    appId: '1:893946047140:ios:b1f390700c8a21587ad431',
    messagingSenderId: '893946047140',
    projectId: 'voygers-9ec9b',
    storageBucket: 'voygers-9ec9b.appspot.com',
    iosClientId: '893946047140-j298illbv8kdpf83lfcqs2cc0bp6ttrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.voygares',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLZU6ZQGz1NSgvtuJSfU57AkwdbPrIK3M',
    appId: '1:893946047140:ios:b1f390700c8a21587ad431',
    messagingSenderId: '893946047140',
    projectId: 'voygers-9ec9b',
    storageBucket: 'voygers-9ec9b.appspot.com',
    iosClientId: '893946047140-j298illbv8kdpf83lfcqs2cc0bp6ttrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.voygares',
  );
}
